Orionis Docs

diff --git a/.github/workflows/jekyll-gh-pages.yml b/.github/workflows/jekyll-gh-pages.yml
--- a/.github/workflows/jekyll-gh-pages.yml
+++ b/.github/workflows/jekyll-gh-pages.yml
@@ -37,7 +37,12 @@ jobs:
         run: npm install
 
       - name: Build with VitePress
-        run: npm run build
+        run: |
+          if [ ! -f package.json ]; then
+            echo "Error: package.json not found in the repository."
+            exit 1
+          fi
+          npm run docs:build
 
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
